[package]
name = "async-tests"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.0", features = ["full"] }
tokio-util = "0.7"
sysinfo = "0.37.2"
tracing = "0.1"
rouille = "3.6.2"
hostname = "0.4.2"
